import bottomup from "../../assets/strategy-explore/bottomup.webp";
import eventdriven from "../../assets/strategy-explore/eventdriven.webp";
import factor from "../../assets/strategy-explore/factor.webp";
import longshort from "../../assets/strategy-explore/longshort.webp";
import marketBeta from "../../assets/strategy-explore/market-beta.webp";
import target from "../../assets/strategy-explore/target.webp";
import theme from "../../assets/strategy-explore/theme.webp";
import topdown from "../../assets/strategy-explore/topdown.webp";
import trend from "../../assets/strategy-explore/trend.webp";
import volatility from "../../assets/strategy-explore/volatility.webp";

export interface StrategyExploreItem {
  id: string;
  name: string;
  accent: string;
  role: string;
  img: string;
  desc: string;
  keywords: string[];
  directness: string;
  bucket: string;
  accountApplication: string;
  howItWorks: string;
  easyWords: { word: string; meaning: string }[];
}

// 각 전략의 정성 설명은 docs/team/주식 전략을 활용한 연금 포트폴리오 운용안.md 근거다.
// 전략별 자산배분 %·수익률 등 수치는 문서에 근거가 없어 화면에 넣지 않는다(수치 환각 금지 규칙).
export const STRATEGIES: StrategyExploreItem[] = [
  { id: "market-beta", name: "시장 베타 전략", accent: "#4FB6E6", role: "공무원", img: marketBeta, desc: "시장 수익률을 포트폴리오의 기준 수익원으로 활용하는 장기 분산 전략입니다.", keywords: ["시장 수익률", "코어"], directness: "ETF로 구현 가능", bucket: "코어(장기 보유)", accountApplication: "국내외 광범위 지수 ETF를 중심으로 분산합니다. 계좌별 위험자산 한도와 전체 주식 비중을 함께 점검합니다.", howItWorks: "개별 종목의 성패보다 시장 전체의 성장에 투자합니다. 단기 전망에 따라 자주 바꾸기보다, 정한 자산배분을 주기적으로 점검하는 방식입니다.", easyWords: [{ word: "시장 베타", meaning: "시장 전체의 움직임에 따라 수익률이 변하는 특성입니다. 시장 베타 전략은 특정 종목 선택보다 시장 평균 수익률을 추구합니다." }, { word: "지수 ETF", meaning: "코스피200·S&P500처럼 특정 지수를 구성하는 여러 종목에 한 번에 투자하는 ETF입니다." }] },
  { id: "factor", name: "팩터 전략", accent: "#24386E", role: "회계사", img: factor, desc: "재무 건전성·가격 수준·추세처럼 장기 성과와 관련된 기업 특성을 기준으로 ETF를 선택하는 규칙 기반 전략입니다.", keywords: ["기업 특성", "코어 보완"], directness: "ETF로 구현 가능", bucket: "코어 보완", accountApplication: "퀄리티·가치·모멘텀·최소변동성 ETF를 성격이 다른 보조 슬리브로 나눠 편입합니다. 한 팩터에만 집중하지 않는 것이 중요합니다.", howItWorks: "정해 둔 기업 특성을 가진 종목을 편입한 ETF를 활용합니다. 팩터별 성과 차이가 장기간 이어질 수 있으므로, 최근 성과만 보고 비중을 크게 바꾸지 않습니다.", easyWords: [{ word: "팩터", meaning: "회사를 고를 때 보는 공통 특징입니다. 재무지표나 주가 특성에 따라 종목을 체계적으로 분류하는 기준입니다." }, { word: "퀄리티", meaning: "수익성·재무 건전성·이익의 안정성이 상대적으로 높은 기업 특성입니다." }, { word: "가치", meaning: "이익·자산·현금흐름에 비해 주가가 낮은 기업을 찾는 접근입니다." }, { word: "모멘텀", meaning: "상대적으로 강했던 가격 추세가 일정 기간 이어지는 경향을 활용하는 방식입니다." }, { word: "최소변동성", meaning: "시장 대비 가격 변동이 상대적으로 낮은 종목을 선별하는 방식입니다." }] },
  { id: "theme", name: "테마 전략", accent: "#F5871F", role: "스타트업 창업가", img: theme, desc: "산업 구조 변화가 예상되는 분야에 집중해 성장 기회를 찾는 위성 전략입니다.", keywords: ["산업 변화", "위성"], directness: "ETF로 구현 가능", bucket: "위성(보조 비중)", accountApplication: "AI·반도체·바이오·인프라 등 테마 ETF는 코어 포트폴리오와 분리해 제한된 비중으로 편입합니다.", howItWorks: "성장 논리, 밸류에이션, 편입 종목의 집중도를 함께 확인합니다. 기대가 이미 가격에 반영됐을 수 있으므로 한 테마에 연금자산을 집중하지 않습니다.", easyWords: [{ word: "테마 ETF", meaning: "특정 산업·기술·사회 변화와 관련된 여러 기업을 묶어 투자하는 ETF입니다." }, { word: "밸류에이션", meaning: "기업의 이익·자산·성장 전망과 비교해 현재 가격이 높은지 낮은지를 평가하는 기준입니다." }, { word: "집중도", meaning: "ETF 성과가 소수 종목이나 한 산업에 얼마나 크게 좌우되는지를 나타내는 정도입니다." }] },
  { id: "topdown", name: "탑다운 전략", accent: "#3B4148", role: "거시경제 애널리스트", img: topdown, desc: "금리·물가·경기 같은 거시 환경을 먼저 분석한 뒤 국가·산업·자산군 비중을 조정하는 전략입니다.", keywords: ["거시 환경", "자산배분"], directness: "ETF로 구현 가능", bucket: "위성(보조 비중)", accountApplication: "국가·산업 ETF와 채권 ETF의 비중을 조정할 때 활용할 수 있습니다. 계좌 규칙과 위험자산 한도 안에서만 비중을 변경합니다.", howItWorks: "경제지표가 자산 가격에 미칠 가능성을 점검하고, 그 결과를 자산배분에 제한적으로 반영합니다. 하나의 거시 전망이 틀릴 수 있으므로 포트폴리오 전체를 한 방향에 걸지 않습니다.", easyWords: [{ word: "거시경제", meaning: "금리·물가·고용·경기처럼 국가 또는 세계 경제 전반의 흐름을 다루는 분야입니다." }, { word: "자산배분", meaning: "주식·채권·현금 등 자산군 사이에 자금을 나누는 의사결정입니다." }, { word: "듀레이션", meaning: "금리 변화에 대한 채권 가격의 민감도입니다. 일반적으로 듀레이션이 길수록 금리 변화에 더 크게 반응합니다." }] },
  { id: "bottomup", name: "바텀업 전략", accent: "#1E9E5D", role: "기업실사 담당자", img: bottomup, desc: "경제 전망보다 개별 기업의 경쟁력·재무상태·성장성을 우선 분석해 투자 대상을 고르는 전략입니다.", keywords: ["기업 분석", "위성"], directness: "ETF·펀드로 구현 가능", bucket: "위성(보조 비중)", accountApplication: "운용 철학과 편입 종목이 명확한 액티브 주식형 펀드 또는 ETF를 제한된 비중으로 검토합니다.", howItWorks: "매출 성장, 이익률, 재무구조, 경쟁우위를 중심으로 기업을 평가합니다. 개별 기업 판단의 오류 가능성이 있으므로 분산된 펀드·ETF와 작은 비중을 우선합니다.", easyWords: [{ word: "바텀업", meaning: "경제 전체의 전망보다 개별 기업의 실적과 경쟁력을 먼저 분석하는 투자 접근입니다." }, { word: "액티브 펀드", meaning: "운용사가 지수 구성 그대로 따르지 않고, 자체 분석으로 종목을 골라 운용하는 펀드입니다." }, { word: "GARP", meaning: "Growth At a Reasonable Price의 약자로, 성장성이 있으면서 가격 부담이 과도하지 않은 기업을 찾는 방식입니다." }] },
  { id: "target", name: "타깃 전략", accent: "#333333", role: "프리랜서 겸 공무원 부업러", img: target, desc: "은퇴 목표 시점에 맞춰 주식·채권·현금 비중을 점진적으로 조정하는 생애주기 전략입니다.", keywords: ["은퇴 시점", "생애주기"], directness: "ETF·TDF로 구현 가능", bucket: "은퇴 시점 관리", accountApplication: "은퇴 예정 시점과 손실 감내 수준을 기준으로 자산군 비중을 정합니다. TDF를 활용할 때도 실제 편입 자산과 보수를 확인합니다.", howItWorks: "은퇴까지 시간이 길면 성장자산 비중을 높게 두고, 은퇴가 가까워질수록 채권·현금 비중을 늘립니다. 목표 시점이 같아도 개인의 소득·자산·손실 감내 수준에 따라 배분은 달라질 수 있습니다.", easyWords: [{ word: "위험자산", meaning: "주식처럼 가격 변동이 크고 원금 손실 가능성이 있는 자산입니다." }, { word: "안정화 자산", meaning: "채권·현금성 자산처럼 포트폴리오 변동성을 낮추는 역할을 하는 자산입니다." }, { word: "글라이드패스", meaning: "은퇴 시점이 가까워질수록 자산배분을 어떻게 바꿀지 정한 경로입니다." }, { word: "TDF", meaning: "Target Date Fund의 약자로, 목표 은퇴 시점에 맞춰 자산배분을 자동 조정하도록 설계된 펀드입니다." }] },
  { id: "volatility", name: "변동성 관리 전략", accent: "#9CA7AE", role: "리스크 매니저", img: volatility, desc: "포트폴리오의 가격 변동 폭을 관리하기 위해 주식·채권·현금 비중을 조절하는 위험관리 전략입니다.", keywords: ["변동성", "위험관리"], directness: "ETF로 구현 가능", bucket: "위험관리", accountApplication: "저변동 ETF와 채권·현금성 자산을 조합해 목표 변동성에 맞는 비중을 관리합니다. 계좌별 위험자산 한도는 별도로 지켜야 합니다.", howItWorks: "시장 변동성이 커지면 위험자산 비중을 낮추고 안정화 자산 비중을 높이는 방식을 사용합니다. 손실을 없애는 전략은 아니며, 상승장에서 시장 수익률을 일부 놓칠 수 있습니다.", easyWords: [{ word: "변동성", meaning: "수익률이 평균 주변에서 얼마나 크게 오르내리는지를 나타내는 지표입니다." }, { word: "저변동 ETF", meaning: "시장 평균보다 가격 변동이 낮았던 종목을 중심으로 구성한 ETF입니다." }, { word: "리밸런싱", meaning: "정한 목표 비중에서 벗어난 자산을 점검해 포트폴리오 비중을 다시 맞추는 과정입니다." }] },
  { id: "longshort", name: "롱숏·시장중립 전략", accent: "#7B4FC0", role: "헤지펀드 매니저", img: longshort, desc: "상승이 기대되는 자산과 하락 위험을 줄이는 포지션을 함께 활용해 시장 방향에 대한 노출을 낮추려는 전략입니다.", keywords: ["시장중립", "상품 확인"], directness: "계좌 적격 상품 확인 필요", bucket: "위성(보조 비중)", accountApplication: "연금계좌에서 편입 가능한 시장중립·절대수익형 펀드가 있는 경우에만 검토합니다. 상품의 투자 방식·비용·유동성을 먼저 확인합니다.", howItWorks: "매수 포지션과 헤지 포지션을 함께 운용해 시장 베타를 낮추는 것을 목표로 합니다. 복잡한 파생상품 또는 공매도 구조를 사용할 수 있어, 상품 설명서와 위험을 충분히 확인해야 합니다.", easyWords: [{ word: "롱", meaning: "자산 가격의 상승에서 수익을 기대하는 매수 포지션입니다." }, { word: "숏", meaning: "자산 가격 하락에 대비하거나 하락에서 수익을 기대하도록 설계된 포지션입니다." }, { word: "시장중립", meaning: "시장 전체의 상승·하락 영향보다 종목·전략 간 상대 성과에 더 노출되도록 설계하는 방식입니다." }, { word: "절대수익", meaning: "시장 지수 대비 성과보다, 시장 방향과 관계없이 양(+)의 수익을 추구하는 운용 목표입니다. 달성이 보장되지는 않습니다." }] },
  { id: "eventdriven", name: "이벤트드리븐 전략", accent: "#F5C518", role: "M&A 전문 변호사·자문역", img: eventdriven, desc: "합병·분할·자사주 매입 등 기업 이벤트가 가격에 반영되는 과정에서 기회를 찾는 전략입니다.", keywords: ["기업 이벤트", "상품 확인"], directness: "계좌 적격 상품 확인 필요", bucket: "위성(보조 비중)", accountApplication: "연금계좌에서 편입 가능한 관련 펀드가 있을 때만 검토합니다. 단일 이벤트에 직접 투자하기보다 분산된 상품의 운용 방식과 위험을 확인합니다.", howItWorks: "공시된 기업 이벤트의 성사 가능성, 일정, 가격 차이를 분석합니다. 거래 무산·일정 변경·규제 변수로 손실이 발생할 수 있으므로 코어 자산을 대체하는 방식으로 사용하지 않습니다.", easyWords: [{ word: "기업행동", meaning: "합병·분할·유상증자·자사주 매입처럼 기업의 자본 구조나 소유 관계에 영향을 주는 사건입니다." }, { word: "합병차익거래", meaning: "합병 발표 뒤 인수가격과 시장가격의 차이가 좁혀질 가능성을 활용하는 전략입니다." }, { word: "스페셜 시추에이션", meaning: "기업에 발생한 특정 사건이 가치와 가격에 미치는 영향을 분석하는 투자 상황을 뜻합니다." }] },
  { id: "trend", name: "추세추종·글로벌 매크로 전략", accent: "#2F6FE0", role: "국제 정세 담당 애널리스트", img: trend, desc: "여러 자산의 가격 추세와 글로벌 경제 환경을 규칙에 따라 활용하는 멀티에셋 전략입니다.", keywords: ["추세", "멀티에셋"], directness: "계좌 적격 상품 확인 필요", bucket: "위성(보조 비중)", accountApplication: "연금계좌에서 편입 가능한 멀티에셋 또는 글로벌 매크로 펀드가 있을 때만 제한된 비중으로 검토합니다.", howItWorks: "주식·채권·원자재·통화 등 여러 자산의 추세와 거시 환경을 함께 점검합니다. 추세가 자주 바뀌는 구간에서는 손실과 매매 비용이 커질 수 있어 규칙과 비용을 확인해야 합니다.", easyWords: [{ word: "추세추종", meaning: "가격이 일정 방향으로 움직이는 경향을 규칙으로 포착해 활용하는 전략입니다." }, { word: "글로벌 매크로", meaning: "국가별 금리·물가·경기·환율 변화가 자산가격에 미치는 영향을 분석하는 투자 접근입니다." }, { word: "멀티에셋", meaning: "주식·채권·원자재·현금 등 여러 자산군을 함께 운용하는 방식입니다." }] },
];
